force-app/main/default/objects/Session__c/fields/End_Time_c__c.field-meta.xml
<CustomField>
    <fullName>End_Time_c__c</fullName>
    <label>End_Time__c</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level__c</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Session_Date__c</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time_c__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_c__c</fullName>
    <label>Start_Time__c</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Speciality_c__c.field-meta.xml
<CustomField>
    <fullName>Speciality_c__c</fullName>
    <label>Speciality__c</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker_Assignment__c/Speaker_Assignment__c.object-meta.xml
<CustomObject>
    <label>Speaker_Assignment</label>
    <nameField>
        <label>Speaker_Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker_Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker_Assignment__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Speaker_Assignments</relationshipLabel>
    <relationshipName>Speaker_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker_Assignment__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Speaker_Assignments</relationshipLabel>
    <relationshipName>Speaker_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SpeakerController.cls
public with sharing class SpeakerController {


    @AuraEnabled(cacheable=true)
    public static List<Speaker__c> searchSpeakers(String name, String speciality) {

        String query =
            'SELECT Id, Name, Email__c, Bio__c, Speciality_c__c ' +
            'FROM Speaker__c WHERE Id != null';

        if (String.isNotBlank(name)) {
            query += ' AND Name LIKE \'%' + String.escapeSingleQuotes(name) + '%\'';
        }

        if (String.isNotBlank(speciality)) {
            query += ' AND Speciality_c__c = \'' + String.escapeSingleQuotes(speciality) + '\'';
        }

        return Database.query(query);
    }

  
    @AuraEnabled(cacheable=true)
    public static Speaker__c getSpeakerById(Id speakerId) {
        return [
            SELECT Id, Name, Bio__c,Speciality_c__c
            FROM Speaker__c
            WHERE Id = :speakerId
            LIMIT 1
        ];
    }

    
    @AuraEnabled(cacheable=true)
    public static Boolean checkAvailability(Id speakerId, Date sessionDate) {

        Integer countAssignments = [
            SELECT COUNT()
            FROM Speaker_Assignment__c
            WHERE Speaker__c = :speakerId
            AND Session__r.Session_Date__c = :sessionDate
        ];

        return countAssignments == 0;
    }

    
    @AuraEnabled
    public static void createAssignment(Id speakerId, Date sessionDate) {
        Id sessionId = getSessionForDate(sessionDate);
        Speaker_Assignment__c sa = new Speaker_Assignment__c(
            Name='Speakers',
            Speaker__c = speakerId,
            Session__c = sessionId
        );

        insert sa;
    }
    @AuraEnabled
public static Id getSessionForDate(Date sessionDate) {
   List<Session__c> sessions = [
        SELECT Id
        FROM Session__c
        WHERE Session_Date__c = :sessionDate
        LIMIT 1
    ];
           
    if (!sessions.isEmpty()) {
        return sessions[0].Id;
    }

    
    Session__c newSession = new Session__c(
        Title__c = 'Auto Session - ' + sessionDate,
        Session_Date__c = sessionDate,
        Start_Time_c__c = Time.newInstance(10, 0, 0, 0),
        End_Time_c__c = Time.newInstance(11, 0, 0, 0),
        Level__c = 'Beginner'
    );

    insert newSession;
    return newSession.Id;
}
    
    @AuraEnabled(cacheable=true)
public static List<String> getBookedDates(Id speakerId) {

    List<String> bookedDates = new List<String>();

    for (AggregateResult ar : [
        SELECT Session__r.Session_Date__c d
        FROM Speaker_Assignment__c
        WHERE Speaker__c = :speakerId
        GROUP BY Session__r.Session_Date__c
    ]) {
        bookedDates.add(String.valueOf(ar.get('d')));
    }

    return bookedDates;
}

}